<a href="https://colab.research.google.com/github/ny-yo/KK_proto/blob/main/cat_dog_classify.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#犬と猫を分類するマルチラベル分類のモデルを作成

AI Academyの下記を参照した  
https://aiacademy.jp/texts/show/?id=164

#google driveのマウント

In [ ]:
from google.colab import drive #インポート
drive.mount('/content/drive/') #GoogleDriveのマウント

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


#画像収集ライブラリicawlerで画像データをダウンロード  -> 余計な画像もダウンロードされてしまうため推論の制度が悪い  
#そのためkaggleの犬猫分類データセットを使うことにした
bingだと動作したがgoogleimageだとダウンロードできず

In [ ]:
#pythonの画像収集ライブラリ
!pip install icrawler

In [ ]:
from icrawler.builtin import BingImageCrawler

# 猫の画像を100枚取得
#crawler = BingImageCrawler(storage={"root_dir": "drive/MyDrive/KK_proto/images/cat"})
#crawler.crawl(keyword="猫", max_num=1000)

In [ ]:
from icrawler.builtin import BingImageCrawler

# 犬の画像を100枚取得
#crawler = BingImageCrawler(storage={"root_dir": "drive/MyDrive/KK_proto/images/dog"})
#crawler.crawl(keyword="犬", max_num=1000)

#データの整形と学習データの作成

In [ ]:
from PIL import Image
import os, glob
import numpy as np
from PIL import ImageFile
# IOError: image file is truncated (0 bytes not processed)回避のため
ImageFile.LOAD_TRUNCATED_IMAGES = True

classes = ["dog", "cat"]
num_classes = len(classes)
image_size = 64
num_testdata = 400

X_train = []
X_test  = []
y_train = []
y_test  = []

for index, classlabel in enumerate(classes):
    print(classlabel)
    photos_dir = "drive/MyDrive/KK_proto/kaggle_dataset/train_data/" + classlabel
    #print(photos_dir)
    files = glob.glob(photos_dir + "/*")
    #print(files)
    for i, file in enumerate(files):
        #print(file)
        image = Image.open(file)
        image = image.convert("RGB")
        image = image.resize((image_size, image_size))
        data = np.asarray(image)
        if i < num_testdata:
            X_test.append(data)
            y_test.append(index)
        else:

            # angleに代入される値
            # -20
            # -15
            # -10
            #  -5
            # 0
            # 5
            # 10
            # 15
            # 画像を5度ずつ回転
            for angle in range(-20, 20, 5):

                img_r = image.rotate(angle)
                data = np.asarray(img_r)
                X_train.append(data)
                y_train.append(index)
                # FLIP_LEFT_RIGHT　は 左右反転
                img_trains = img_r.transpose(Image.FLIP_LEFT_RIGHT)
                data = np.asarray(img_trains)
                X_train.append(data)
                y_train.append(index)

X_train = np.array(X_train)
X_test  = np.array(X_test)
y_train = np.array(y_train)
y_test  = np.array(y_test)

xy = (X_train, X_test, y_train, y_test)
print(y_test)
print(y_test.shape)
np.save("drive/MyDrive/KK_proto/dog_cat.npy", xy)

dog
cat
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 

/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


#学習フェーズ

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.optimizers import RMSprop
from keras.utils import np_utils
import keras
import numpy as np

classes = ["dog", "cat"]
num_classes = len(classes)
image_size = 64

"""
データを読み込む関数
"""
def load_data():
    X_train, X_test, y_train, y_test = np.load("/content/drive/MyDrive/KK_proto/dog_cat.npy", allow_pickle=True)
    # 入力データの各画素値を0-1の範囲で正規化(学習コストを下げるため)
    X_train = X_train.astype("float") / 255
    X_test  = X_test.astype("float") / 255
    # to_categorical()にてラベルをone hot vector化
    y_train = np_utils.to_categorical(y_train, num_classes)
    y_test  = np_utils.to_categorical(y_test, num_classes)

    return X_train, y_train, X_test, y_test

"""
モデルを学習する関数
"""
def train(X, y, X_test, y_test):
    model = Sequential()

    # Xは(1200, 64, 64, 3)
    # X.shape[1:]とすることで、(64, 64, 3)となり、入力にすることが可能です。
    model.add(Conv2D(32,(3,3), padding='same',input_shape=X.shape[1:]))
    model.add(Activation('relu'))
    model.add(Conv2D(32,(3,3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.1))

    model.add(Conv2D(64,(3,3), padding='same'))
    model.add(Activation('relu'))
    model.add(Conv2D(64,(3,3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(512))
    model.add(Activation('relu'))
    model.add(Dropout(0.45))
    model.add(Dense(2))
    model.add(Activation('softmax'))

    # https://keras.io/ja/optimizers/
    # 今回は、最適化アルゴリズムにRMSpropを利用
    opt = RMSprop(learning_rate=0.00005, decay=1e-6)
    # https://keras.io/ja/models/sequential/
    model.compile(loss='categorical_crossentropy',optimizer=opt,metrics=['accuracy'])
    model.fit(X, y, batch_size=28, epochs=20)
    # HDF5ファイルにKerasのモデルを保存
    #model.save('./cnn.h5')
    model.save('/content/drive/MyDrive/KK_proto/cnn.h5')

    return model

"""
メイン関数
データの読み込みとモデルの学習を行います。
"""
def main():
    # データの読み込み
    X_train, y_train, X_test, y_test = load_data()

    # モデルの学習
    model = train(X_train, y_train, X_test, y_test)

main()

Epoch 1/20
1143/1143 [==============================] - 41s 9ms/step - loss: 0.6650 - accuracy: 0.5878
Epoch 2/20
1143/1143 [==============================] - 10s 8ms/step - loss: 0.5595 - accuracy: 0.7126
Epoch 3/20
1143/1143 [==============================] - 10s 8ms/step - loss: 0.4851 - accuracy: 0.7671
Epoch 4/20
1143/1143 [==============================] - 10s 8ms/step - loss: 0.4396 - accuracy: 0.7947
Epoch 5/20
1143/1143 [==============================] - 10s 8ms/step - loss: 0.4025 - accuracy: 0.8175
Epoch 6/20
1143/1143 [==============================] - 10s 9ms/step - loss: 0.3635 - accuracy: 0.8380
Epoch 7/20
1143/1143 [==============================] - 10s 9ms/step - loss: 0.3307 - accuracy: 0.8581
Epoch 8/20
1143/1143 [==============================] - 10s 9ms/step - loss: 0.2967 - accuracy: 0.8769
Epoch 9/20
1143/1143 [==============================] - 10s 8ms/step - loss: 0.2779 - accuracy: 0.8851
Epoch 10/20
1143/1143 [==============================] - 10s 9ms/step - l

#推論モデル
テスト画像が犬or猫のどちらかを推論するモデル

In [ ]:
import keras
import sys, os
import numpy as np
from keras.models import load_model

imsize = (64, 64)

"""
dog1.jpgというファイル名の画像をGoogle Colab上にアップロードする方法は2通りあります。
1つが、下記のコードを実行し画像をアップロードする方法
from google.colab import files
uploaded = files.upload()
2つが、Colab左メニューの>アイコンを押して、目次、コード スニペット、ファイル
の3つ表示されるますが、右のファイルタブから画像をアップロードする方法です。
このファイルタブをクリックするとアップロードと更新の2つがありますが、
アップロードを押すと画像をアップロードすることが可能です。
"""

testpic     = "/content/drive/MyDrive/KK_proto/11.jpg"
test_img_folder = "/content/drive/MyDrive/KK_proto/kaggle_dataset/test_data/*"
keras_param = "/content/drive/MyDrive/KK_proto/cnn.h5"

def load_image(path):
    img = Image.open(path)
    img = img.convert('RGB')
    # 学習時に、(64, 64, 3)で学習したので、画像の縦・横は今回 変数imsizeの(64, 64)にリサイズします。
    img = img.resize(imsize)
    # 画像データをnumpy配列の形式に変更
    img = np.asarray(img)
    img = img / 255.0
    return img

#from google.colab import files
#uploaded = files.upload()

model = load_model(keras_param)
dog_num = 0
cat_num = 0
file_num = 0

files = glob.glob(test_img_folder)
for file in files:
    img = load_image(file)
    prd = model.predict(np.array([img]))
    print(prd) # 精度の表示
    prelabel = np.argmax(prd, axis=1)
    if prelabel == 0:
        print(">>> 犬  filename->%s" % file)
        dog_num += 1

    elif prelabel == 1:
        print(">>> 猫  filename->%s" % file)
        cat_num += 1
    file_num += 1

print("result")
print("dog -> %f" % (dog_num/file_num))
print("cat -> %f" % (cat_num/file_num))

[[0.60652024 0.3934798 ]]
>>> 犬  filename->/content/drive/MyDrive/KK_proto/kaggle_dataset/test_data/test_001.jpg
[[0.21164265 0.7883574 ]]
>>> 猫  filename->/content/drive/MyDrive/KK_proto/kaggle_dataset/test_data/53.jpg
[[1.3624796e-07 9.9999988e-01]]
>>> 猫  filename->/content/drive/MyDrive/KK_proto/kaggle_dataset/test_data/10.jpg
[[1.5580007e-06 9.9999845e-01]]
>>> 猫  filename->/content/drive/MyDrive/KK_proto/kaggle_dataset/test_data/37.jpg
[[0.9967302  0.00326981]]
>>> 犬  filename->/content/drive/MyDrive/KK_proto/kaggle_dataset/test_data/30.jpg
[[3.6720826e-10 1.0000000e+00]]
>>> 猫  filename->/content/drive/MyDrive/KK_proto/kaggle_dataset/test_data/38.jpg
[[0.3013018  0.69869816]]
>>> 猫  filename->/content/drive/MyDrive/KK_proto/kaggle_dataset/test_data/29.jpg
[[1.548954e-08 1.000000e+00]]
>>> 猫  filename->/content/drive/MyDrive/KK_proto/kaggle_dataset/test_data/35.jpg
[[9.9967885e-01 3.2115536e-04]]
>>> 犬  filename->/content/drive/MyDrive/KK_proto/kaggle_dataset/test_data/2.jpg
[[0.